name: TAP tests

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tap: [tap1, tap2, tap3, tap4, tap5, tap6, tap7, tap8, tap9, tap10, tap11, tap12, tap13, tap14, tap15, tap16, tap17, tap18, tap19, tap20]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # this Action should follow steps to set up Python build environment
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"

      # Runs a set of commands using the runners shell
      - name: run Django/Turkle server
        run: |
          echo 'Python version'
          python --version
          python3 --version
          echo 'Moving to src directory'
          cd src
          echo 'Print the current directory'
          pwd
          echo 'List the files in the current directory'
          ls -l
          echo 'Clone Turkle'
          ./1_run_website.sh & sleep 30
          echo 'Generate the input files'
          python 2_generate_input_csv.py
          echo 'Upload the tasks'
          python 3_upload_tasks.py

      # Run the TAP tests
      - name: run TAP tests
        run: |
          cd src
          echo 'run TAP tests ${{ matrix.tap }}'
          python TAP_tests.py ${{ matrix.tap }}